MartialArtsSchool/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MartialArtsSchool.Models;

public partial class Lesson
{
    public int IdLesson { get; set; }

    [Required, MinLength(2, ErrorMessage = "Należy wpisać minimum 2 znaki"),
     MaxLength(8, ErrorMessage = "Wpisano zbyt wiele znaków"),
     RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Proszę użyć tylko liter, bez znaków specjalnych. Proszę o podanie tylko pierwszego imienia")]
    public string Name { get; set; } = null!;

    [MinLength(20, ErrorMessage = "Należy wpisać minimum 20 znaków"),
     MaxLength(255, ErrorMessage = "Wpisano zbyt wiele znaków")]
    public string Description { get; set; } = null!;

    public virtual ICollection<Member> IdMemebers { get; } = null!;
}

MartialArtsSchool/Controllers/LessonController.cs
using MartialArtsSchool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MartialArtsSchool.Controllers
{
    public class LessonController : Controller
    {
        private readonly MarArtDbContext _db;

        public LessonController(MarArtDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Lesson> lessons = _db.Lessons;
            return View(lessons);
        }

        //GET CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST CREATE
        [HttpPost]
        public IActionResult Create(Lesson obj)
        {
            if (ModelState.IsValid)
            {
                _db.Lessons.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Lesson created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET VIEW
        public IActionResult View(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Lessons.Include(l => l.IdMemebers).SingleOrDefault(l => l.IdLesson == id);

            ViewBag.LessonList = new SelectList(_db.Lessons, "IdLesson", "Name");
            // poczytać

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        // bez metody post, bo nic nie edytuję

        //GET EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Lessons.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST EDIT
        [HttpPost]
        public IActionResult Edit(Lesson obj)
        {
            if (ModelState.IsValid)
            {
                _db.Lessons.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Lessons updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Lessons.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST DELETE
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Lessons.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Lessons.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Lesson deleted successfully";
            return RedirectToAction("Index");

        }

        //GET VIEW
        public IActionResult ViewMembers(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var ter = _db.Lessons.Find(id);
            IEnumerable<Member> categoryFromDb2 = _db.Lessons.Find(id).IdMemebers;
  
            if (categoryFromDb2 == null)
            {
                return NotFound();
            }

            return View(categoryFromDb2);
        }

       
    }
}

MartialArtsSchool/Controllers/MemberController.cs
using MartialArtsSchool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MartialArtsSchool.Controllers
{
    public class MemberController : Controller
    {
        private readonly MarArtDbContext _db;

        public MemberController(MarArtDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Member> members = _db.Members;
            return View(members);
        }

        //GET CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST CREATE
        [HttpPost]
        public IActionResult Create(Member obj)
        {
            if (ModelState.IsValid)
            {
                _db.Members.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Member created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET VIEW
        public IActionResult View(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Members.Include(l => l.IdLessons).SingleOrDefault(l => l.IdMemeber == id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            var allLessons = _db.Lessons.ToList();
            var lessonsToExclude = categoryFromDb.IdLessons.ToList();
            var lessonsToShow = allLessons.Except(lessonsToExclude).ToList();

            ViewBag.LessonList = new SelectList(lessonsToShow, "IdLesson", "Name");
            // poczytać

            return View(categoryFromDb);
        }
        // bez metody post, bo nic nie edytuję

        //GET EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Members.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST EDIT
        [HttpPost]
        public IActionResult Edit(Member obj)
        {
            if (ModelState.IsValid)
            {
                _db.Members.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Members updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Members.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST DELETE
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Members.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Members.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Member deleted successfully";
            return RedirectToAction("Index");

        }

        // ===========================================================

        //GET ASSIGN
        public IActionResult Assign(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var baseCategory = _db.Members.Include(l => l.IdLessons).SingleOrDefault(l => l.IdMemeber == id);

            if (baseCategory == null)
            {
                return NotFound();
            }

            var categoryFromDb = _db.Lessons.Except(baseCategory.IdLessons);

            ViewBag.LessonList = new SelectList(categoryFromDb, "IdLesson", "Name");
            // poczytać

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

    }
}

MartialArtsSchool/Views/Lesson/Create.cshtml
@model MartialArtsSchool.Models.Lesson

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdLesson" class="control-label"></label>
                <input asp-for="IdLesson" class="form-control" />
                <span asp-validation-for="IdLesson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="back-link">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MartialArtsSchool/Views/Lesson/Delete.cshtml
@model MartialArtsSchool.Models.Lesson

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Lesson</h1>

<h3>Are you sure you want to delete this Lesson?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdLesson" />
        <input type="submit" value="Delete lesson" class="btn btn-danger" />
        <a asp-action="Index" class="back-link">Back to List of Lessons</a>
    </form>
</div>

MartialArtsSchool/Views/Lesson/Edit.cshtml
@model MartialArtsSchool.Models.Lesson

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdLesson" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="back-link">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MartialArtsSchool/Views/Lesson/Index.cshtml
@model IEnumerable<MartialArtsSchool.Models.Lesson>

@{
    ViewData["Title"] = "Index";
}

<h1>List of Lessons</h1>

<p>
    <a asp-controller="Lesson" asp-action="Create" class="create-link">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Course Name
            </th>
            <th>
                Description
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-controller="Lesson" asp-action="Edit" asp-route-id="@item.IdLesson">Edit</a> |
                <a asp-controller="Lesson" asp-action="View" asp-route-id="@item.IdLesson">Details</a> |
                <a asp-controller="Lesson" asp-action="Delete" asp-route-id="@item.IdLesson">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MartialArtsSchool/Views/Lesson/View.cshtml
@model MartialArtsSchool.Models.Lesson

@{
    ViewData["Title"] = "View";
}

<h1>Lesson Details</h1>

<div class="details-container">
    <h4>Lesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdLesson" class="back-link">Edit</a>
    <a asp-action="Index" class="back-link">Back to List</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Birth Date
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.IdMemebers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
            </tr>
        }
    </tbody>
</table>

<select asp-for="IdLesson" asp-items="ViewBag.LessonList" class="form-control"></select>

MartialArtsSchool/Views/Lesson/ViewMembers.cshtml
@model IEnumerable<MartialArtsSchool.Models.Member>

@{
    ViewData["Title"] = "ViewMembers";
}

<h1>Lesson Members</h1>
<table class="table">
<thead>
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Birth Date
        </th>
        <th>
            Actions
        </th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                <a asp-controller="Member" asp-action="View" asp-route-id="@item.IdMemeber">Details</a> |
            </td>
        </tr>
    }
</tbody>
</table>
<div>
    <a asp-action="Index" class="back-link">Back to List</a>
</div>